[package]
name = "braveblock"
version = "0.1.0"
authors = ["Gal Ben David <gal@intsights.com>"]
edition = "2018"

[lib]
name = "braveblock"
crate-type = ["cdylib"]

[dependencies.adblock]
version = "0.3"

[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]
