name: Deploy
on:
  release:
    types: [published]

jobs:
  deploy:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip maturin
      - name: Build Python package
        run: maturin build --release --no-sdist --strip --interpreter python${{matrix.python_version}} --out dist
      - name: Publish to PyPi
        run: maturin publish --username __token__ --no-sdist --interpreter python${{matrix.python_version}}
        env:
          MATURIN_PASSWORD: ${{ secrets.pypi_password }}
